//! Deterministic corpus fixtures for the support-gate validators
//! (Plan 618 T8) + the deterministic Gaussian sampler they ride.
//!
//! Everything here is OFFLINE test/certification material — allocation is
//! fine, and the sampler is deliberately **libm-free** (a central-limit sum
//! of 12 uniforms — the `conformal/floor_harness` precedent): only `+`
//! and `×`, so fixture bytes are bit-identical on every IEEE platform
//! from the same seed. Tails are bounded at ±6σ (documented, and
//! irrelevant for gate fixtures — nothing in the acceptance instruments
//! lives out there; the far-out probes are generated by displacement,
//! not sampling).

use super::mixture::DiagGmm;
use super::projector::SplitMix64;

/// Approximate standard normal via the central-limit sum of 12 uniforms
/// (Irwin–Hall; bounded ±6σ, libm-free — see module docs).
#[inline]
pub(crate) fn clt_normal(rng: &mut SplitMix64) -> f32 {
    let mut sum = 0.0f32;
    for _ in 0..12 {
        sum += rng.next_f32();
    }
    sum - 6.0
}

/// Deterministic fixture set: an in-support blob (with KNOWN true
/// parameters — the T7 bound needs them), a generic reference, off-domain
/// probes, and the discriminator-extrapolation probes the T6 canary
/// needs. BLAKE3-pinnable via the mixtures' own commitments + a
/// sample-content commitment (`content_commitment`).
#[derive(Debug, Clone)]
pub struct FixtureSet<const E: usize, const K: usize> {
    /// The TRUE in-support mixture (the fixture's known P).
    pub true_pos: DiagGmm<E, K>,
    /// The generic reference mixture (Φ_neg).
    pub neg: DiagGmm<E, K>,
    /// Training samples drawn from `true_pos`.
    pub pos_train: Vec<Vec<f32>>,
    /// Held-out samples drawn from `true_pos`.
    pub pos_held_out: Vec<Vec<f32>>,
    /// Off-domain blob samples (a third, well-separated mixture).
    pub planted_b: Vec<Vec<f32>>,
    /// Far-out probes along the discriminator's positive normal — the
    /// leak-by-construction canary positions (beyond the positive blob
    /// along `w = normalize(μ̄_A − μ̄_B)`).
    pub extrapolation: Vec<Vec<f32>>,
}

/// Build a fixture at a given `separation` (scales inter-blob distance —
/// the T7 monotonicity arm varies this).
#[must_use]
pub fn build_fixture<const E: usize, const K: usize>(
    seed: u64,
    n_train: usize,
    n_held_out: usize,
    n_b: usize,
    separation: f32,
) -> FixtureSet<E, K> {
    let mut rng = SplitMix64::new(seed);

    // ── True positive mixture: K centroids on the sphere of radius
    // `separation` (random high-E directions are near-orthogonal — good
    // inter-centroid spread AND a bounded shell, so the off-domain blob
    // at 6·separation and the extrapolation probes at k·separation sit
    // genuinely OUTSIDE the positive support).
    let mut centroids = [[0f32; E]; K];
    for c in centroids.iter_mut() {
        for v in c.iter_mut() {
            *v = clt_normal(&mut rng);
        }
        let norm = (c.iter().map(|x| x * x).sum::<f32>()).sqrt();
        if norm > 0.0 {
            let inv = separation / norm;
            for v in c.iter_mut() {
                *v *= inv;
            }
        }
    }
    let mut variances = [[0f32; E]; K];
    for row in variances.iter_mut() {
        for v in row.iter_mut() {
            *v = 0.5 + rng.next_f32(); // σ² ∈ [0.5, 1.5)
        }
    }
    let log_weights = [f32::ln(1.0 / K as f32); K];
    let true_pos = DiagGmm::new_unchecked(centroids, log_weights, variances);

    // ── Generic reference: centered at the origin, broad ───────────────
    // Variance 4× the positive blobs' — the reference captures WIDTH.
    let neg_centroids = [[0f32; E]; K];
    let mut neg_variances = [[0f32; E]; K];
    for row in neg_variances.iter_mut() {
        for v in row.iter_mut() {
            *v = 2.0 + 2.0 * rng.next_f32(); // σ² ∈ [2, 4)
        }
    }
    let neg = DiagGmm::new_unchecked(neg_centroids, log_weights, neg_variances);

    // ── Off-domain blob: displaced along a fixed seeded direction ──────
    let mut dir = [0f32; E];
    for v in dir.iter_mut() {
        *v = clt_normal(&mut rng);
    }
    let dir_norm = (dir.iter().map(|x| x * x).sum::<f32>()).sqrt();
    if dir_norm > 0.0 {
        for v in dir.iter_mut() {
            *v /= dir_norm;
        }
    }
    let b_center: Vec<f32> = dir.iter().map(|&d| d * separation * 6.0).collect();

    let pos_train = sample_mixture(&true_pos, &mut rng, n_train);
    let pos_held_out = sample_mixture(&true_pos, &mut rng, n_held_out);
    let planted_b = (0..n_b)
        .map(|_| {
            (0..E)
                .map(|d| b_center[d] + clt_normal(&mut rng))
                .collect::<Vec<f32>>()
        })
        .collect();

    // ── Extrapolation probes: beyond the POSITIVE blob along the
    // discriminator's positive normal `w = normalize(μ̄_A − μ̄_B)`. The
    // leaky discriminator-class gate is GUARANTEED to fire here (it
    // scores `w·x ≫ bias`); a density gate closes (both densities are
    // vanishingly small there — the ratio is decided by tails, and the
    // off-support side loses).
    let pos_mean = mean_of(&true_pos);
    let mut w = [0f32; E];
    for d in 0..E {
        w[d] = pos_mean[d] - b_center[d];
    }
    let w_norm = (w.iter().map(|x| x * x).sum::<f32>()).sqrt();
    if w_norm > 0.0 {
        for v in w.iter_mut() {
            *v /= w_norm;
        }
    }
    let extrapolation = [4.0f32, 6.0, 8.0, 12.0]
        .iter()
        .map(|&k| {
            (0..E)
                .map(|d| pos_mean[d] + w[d] * k * separation)
                .collect::<Vec<f32>>()
        })
        .collect();

    FixtureSet {
        true_pos,
        neg,
        pos_train,
        pos_held_out,
        planted_b,
        extrapolation,
    }
}

/// Deterministic sample from a mixture into a caller buffer: component
/// by weight (cumulative walk, first crossing), then `μ_k + σ_k · z`
/// per dim. The ONE sampler home — the certify instruments consume this
/// (never a second copy).
pub(crate) fn sample_mixture_into<const E: usize, const K: usize>(
    gmm: &DiagGmm<E, K>,
    rng: &mut SplitMix64,
    out: &mut [f32],
) {
    // Cumulative weights over exp(log_weights) — deterministic walk.
    let mut cum = [0f32; K];
    let mut acc = 0.0f32;
    for (k, c) in cum.iter_mut().enumerate() {
        acc += gmm.log_weights[k].exp();
        *c = acc;
    }
    let total = cum[K - 1];
    let u = rng.next_f32() * total;
    let mut comp = K - 1;
    for (k, &c) in cum.iter().enumerate() {
        if u < c {
            comp = k;
            break;
        }
    }
    for ((o, &cen), &var) in out
        .iter_mut()
        .zip(gmm.centroids[comp].iter())
        .zip(gmm.variances[comp].iter())
    {
        *o = cen + var.sqrt() * clt_normal(rng);
    }
}

/// Owned-`Vec` form of [`sample_mixture_into`] (fixture construction).
fn sample_mixture<const E: usize, const K: usize>(
    gmm: &DiagGmm<E, K>,
    rng: &mut SplitMix64,
    n: usize,
) -> Vec<Vec<f32>> {
    let mut out = Vec::with_capacity(n);
    let mut x = vec![0f32; E];
    for _ in 0..n {
        sample_mixture_into(gmm, rng, &mut x);
        out.push(x.clone());
    }
    out
}

/// The mixture's mean vector `Σ_k π_k μ_k`.
fn mean_of<const E: usize, const K: usize>(gmm: &DiagGmm<E, K>) -> [f32; E] {
    let mut out = [0f32; E];
    for (k, &lw) in gmm.log_weights.iter().enumerate() {
        let w = lw.exp();
        for (o, &c) in out.iter_mut().zip(gmm.centroids[k].iter()) {
            *o += w * c;
        }
    }
    out
}
